version: '3'

dotenv: [.env]

tasks:
  env:
    desc: makes .env from .env.example
    cmds:
      - cp .env.example .env

  root:yarn:
    desc: runs 'yarn' in root directory
    cmds:
      - |
        docker run \
          --rm \
          -w /app \
          -v $(pwd)/..:/app \
          $NODE_IMAGE yarn

  docs:yarn:
    desc: runs 'yarn' in 'docs' directory
    cmds:
      - |
        docker run \
          --rm \
          -w /app \
          -v $(pwd)/../docs:/app \
          $NODE_IMAGE yarn

  lib:yarn:
    desc: runs 'yarn' in 'lib' directory
    cmds:
      - |
        docker run \
          --rm \
          -w /app \
          -v $(pwd)/../lib:/app \
          $NODE_IMAGE yarn

  yarn:
    cmds:
      - task root:yarn
      - task docs:yarn
      - task lib:yarn

  lint:
    cmds:
      - |
        docker run \
          --rm \
          -w /app \
          -v $(pwd)/..:/app \
          $NODE_IMAGE /bin/bash -c "yarn lint"

  test:
    desc: runs unit tests of lib
    cmds:
      - |
        docker run --user {{.MY_UID}}:{{.MY_GID}} \
          -v $(pwd)/../lib:/app \
          -w /app \
          $NODE_IMAGE \
          yarn test:unit

  build:prepare:
    desc: creates production build of docs
    cmds:
      - |
        docker run \
          --rm \
          -w /app/docs \
          -v $(pwd)/../docs:/app/docs \
          -v $(pwd)/../lib:/app/lib \
          $NODE_IMAGE /bin/bash -c "yarn build"

  build:
    cmds:
      - task lint
      - task test
      - task build:prepare

  deploy:pages:
    desc: deploy to CloudFlare pages
    cmds:
      - |
        docker run --user $(id -u):$(id -g) \
        --rm \
        -w /app \
        -v $(pwd)/../docs:/app \
        -e CLOUDFLARE_ACCOUNT_ID \
        -e CLOUDFLARE_API_TOKEN \
        $NODE_IMAGE yarn deploy

  deploy:
    desc: Lints, tests, builds and deploys to CloudFlare pages
    cmds:
      - task build
      - task deploy:pages
