services:
  docs:
    image: ${NODE_IMAGE}
    working_dir: /app/docs
    command: yarn dev
    user: ${MY_UID}:${MY_GID}
    volumes:
      - ../docs:/app/docs
      - ../lib:/app/lib

  docs-preview:
    image: ${NODE_IMAGE}
    working_dir: /app/docs
    command: yarn preview
    user: ${MY_UID}:${MY_GID}
    ports:
      - 9000:80
    volumes:
      - ../docs:/app/docs
      - ../lib:/app/lib

  lib-tests-unit:
    image: unit-tests-ui
    user: ${MY_UID}:${MY_GID}
    working_dir: /app
    command: yarn test:unit:ui
    ports:
      - 9010:8000
    volumes:
      - ../lib:/app

  tests-e2e:
    image: ${PLAYWRIGHT_IMAGE}
    user: ${MY_UID}:${MY_GID}
    working_dir: /app
    depends_on:
      - docs
    ports:
      - '9020:8000'
    volumes:
      - ../docs:/app
    command: yarn test:e2e:report

  nginx:
    image: ${NGINX_IMAGE}
    ports:
      - 80:80
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../.dev/tests.html:/var/www/tests/index.html
    depends_on:
      - docs
